---
- name: Manage nginx service
  hosts: webservers
  become: true

  tasks:

    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

    - name: Stop nginx
      ansible.builtin.service:
        name: nginx
        state: stopped
