---
- name: Create application directory
  hosts: webservers
  become: true

  tasks:

    - name: Create directory
      ansible.builtin.file:
        path: /opt/myapp
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Create file
      ansible.builtin.file:
        path: /opt/myapp/config.txt
        state: touch
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Delete file
      ansible.builtin.file:
        path: /opt/myapp/config.txt
        state: absent
