---
- name: Copy configuration
  hosts: webservers
  become: true

  tasks:

    - name: Copy nginx configuration
      ansible.builtin.copy:
        src: ./files/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
        backup: true
