---
- name: Ansbile module (to remote fetch logs from the remote server)
  hosts: webservers
  become: true
  
  tasks:
    - name: Fetch logs from remote server
      ansible.builtin.fetch:
        src: /home/ubuntu/myworkspace/inventory.ini
        dest: /tmp
