---
- name: Collect server logs
  hosts: webservers
  become: true

  tasks:

    - name: Fetch nginx access log
      ansible.builtin.fetch:
        src: /var/log/nginx/access.log
        dest: ./logs/
        flat: false
