---
- name: Run Linux commands
  hosts: webservers

  tasks:

    - name: Check uptime
      ansible.builtin.command:
        cmd: uptime

    - name: Check kernel
      ansible.builtin.command:
        cmd: uname -r

    - name: Check disk
      ansible.builtin.command:
        cmd: df -h
