---
- name: Ansbile module for (execute shell expressions command on remote server)
  hosts: webservers
  become: true
  
  tasks:
    - name: Execute command on remote server
      ansible.builtin.shell:
        cmd: df -h
      register: my_command_output
    
    - name: Display command output
      ansible.builtin.debug:
        var: my_command_output.stdout
