---
- name: Run shell commands
  hosts: webservers

  tasks:

    - name: Find nginx process
      ansible.builtin.shell:
        cmd: "ps aux | grep nginx"

    - name: Check disk usage
      ansible.builtin.shell:
        cmd: "df -h | grep /dev"
