---
- name: Manage Linux users
  hosts: webservers
  become: true

  tasks:

    - name: Create devops user
      ansible.builtin.user:
        name: devops
        state: present
        shell: /bin/bash
        create_home: true

    - name: Delete test user
      ansible.builtin.user:
        name: testuser
        state: absent
        remove: true
