---
- name: Manage Linux groups
  hosts: webservers
  become: true

  tasks:

    - name: Create developers group
      ansible.builtin.group:
        name: developers
        state: present

    - name: Delete old group
      ansible.builtin.group:
        name: oldgroup
        state: absent
    
    - name: Add devops user to developers
      ansible.builtin.user:
        name: devops
        groups:
          - developers
          - docker
        append: true
