---
- name: Ansbile module for (cloning git repository)
  hosts: webservers
  become: true
  
  tasks:
    - name: Clone git repository
      ansible.builtin.git:
        repo: https://github.com/example/my-repo.git
        dest: /tmp/my-repo
