---
- name: Ansbile module for (downloading files from internet)
  hosts: webservers
  become: true
  
  tasks:
    - name: Download file
      ansible.builtin.get_url:
        url: https://example.com/file.tar.gz
        dest: /tmp/file.tar.gz