[webservers]
web01 ansible_host=54.164.166.99 ansible_user=ubuntu

[all:vars]
ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
ansible_host_key_checking=false
